version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_POSTGREST_URL=${VITE_POSTGREST_URL}
        - SERVER_NAME=${SERVER_NAME}
    network_mode: "host"