services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile

  mock-server:
    build:
      context: ./mock-server
      dockerfile: Dockerfile

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"