name: Tests webaplicaiton for feature branches on push

# The workflow event listens to push requests for every new feature branch
on:
  push:
    branches:
      - '!main'
      - '!developer'
      - '*'
    paths:
      - 'client/**'
  workflow_dispatch: # To test the code manually

# Jobs executed (each job has its own runner)
jobs:
  test-web-application: 
    name: 'Run unit tests for web-application' # Runs unit tests found in the test directory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
        working-directory: ./client

      - name: Run Tests
        run: npm run test # Calls a script called test from package.json
        working-directory: ./client
        
  lint-web-application:
      name: 'Lint code for web-application' # Checks linting issues and fixes them
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
  
        - name: Install Dependencies
          run: npm install
          working-directory: ./client
  
        - name: Auto-fix linting issues
          run: npm run lint -- --fix # Calls a script called lint from package.json
          working-directory: ./client
  
        - name: Check if there are linting changes # Checks if any files are modified
          id: git-check-lint
          run: |
            git diff --exit-code || echo "::set-output name=changed::true"
          working-directory: ./client
  
        - name: Commit linting changes # Allows the bot/workflow to apply the changes and commit to the repository
          if: steps.git-check-lint.outputs.changed == 'true'
          run: |
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config user.name "github-actions[bot]"
            changed_files=$(git diff --name-only)
            git commit -am "style: lint fix $changed_files"
            git push
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./client
        
  Format-web-application:
    name: 'Prettify code for web-application' # Cheks prettify issues and beautifies code following the StandardJS coding convention
    runs-on: ubuntu-latest
    needs: lint-web-application
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures all branches and tags are fetched
  
      - name: Install Dependencies
        run: npm install
        working-directory: ./client
  
      - name: Pull latest changes
        run: |
          git pull origin ${GITHUB_REF#refs/heads/} --rebase
        working-directory: ./client
  
      - name: Prettify code
        run: npm run format # Calls a script called prettify from package.json
        working-directory: ./client
  
      - name: Check if there are changes # Checks if any files are modified
        id: git-check
        run: |
          git diff --exit-code || echo "::set-output name=changed::true"
        working-directory: ./client
  
      - name: Commit changes # Allows the bot/workflow to apply the changes and commit to the repository
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          changed_files=$(git diff --name-only)
          git commit -am "style: prettify fix $changed_files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./client

        
  
# Commented out the 'api-server' related jobs